// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1InzTDHGeRdT911-o7zliCTLbuZ7orpc',
    appId: '1:2356601100:web:40d529f1c4cf1a0c4be929',
    messagingSenderId: '2356601100',
    projectId: 'ergodic-test',
    authDomain: 'ergodic-test.firebaseapp.com',
    storageBucket: 'ergodic-test.firebasestorage.app',
    measurementId: 'G-9V24CM2R9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAakw2I26qHTucVRAeQ74GTOM0IXw1TAhg',
    appId: '1:2356601100:android:5269e874af47e7ad4be929',
    messagingSenderId: '2356601100',
    projectId: 'ergodic-test',
    storageBucket: 'ergodic-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZU9DWJAoChto6ictkiXg77XgUxvjarhM',
    appId: '1:2356601100:ios:7bddc8db8054052f4be929',
    messagingSenderId: '2356601100',
    projectId: 'ergodic-test',
    storageBucket: 'ergodic-test.firebasestorage.app',
    iosBundleId: 'com.example.ergodicTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZU9DWJAoChto6ictkiXg77XgUxvjarhM',
    appId: '1:2356601100:ios:7bddc8db8054052f4be929',
    messagingSenderId: '2356601100',
    projectId: 'ergodic-test',
    storageBucket: 'ergodic-test.firebasestorage.app',
    iosBundleId: 'com.example.ergodicTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1InzTDHGeRdT911-o7zliCTLbuZ7orpc',
    appId: '1:2356601100:web:2f52df01b11c05474be929',
    messagingSenderId: '2356601100',
    projectId: 'ergodic-test',
    authDomain: 'ergodic-test.firebaseapp.com',
    storageBucket: 'ergodic-test.firebasestorage.app',
    measurementId: 'G-66WEHG2D3D',
  );
}
